package(default_visibility = ["//visibility:public"])

config_setting(
    name = "raspbian",
    values = {"cpu": "raspbian"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "bionic",
    values = {"cpu": "bionic"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "roborio",
    values = {"cpu": "roborio"},
    visibility = ["//visibility:public"],
)
